# Budget alert configuration for cost monitoring
# Apply this with: gcloud billing budgets create --billing-account=BILLING_ACCOUNT_ID --budget-from-file=deploy/budget-alert.yaml

displayName: "Workplacify Monthly Budget"
amount:
  specifiedAmount:
    currencyCode: "USD"
    units: "25"  # $25 monthly budget
budgetFilter:
  projects:
    - "projects/YOUR_PROJECT_ID"  # Replace with your actual project ID
  services:
    - "services/6F81-5844-456A"  # Cloud Run
    - "services/9662-B51E-5089"  # Cloud SQL
    - "services/95FF-2EF5-5EA1"  # Secret Manager
    - "services/A1E8-BE35-7EBC"  # Container Registry
    - "services/58CD-39A6-95F0"  # Cloud Build
thresholdRules:
  - thresholdPercent: 0.5  # 50% of budget
    spendBasis: CURRENT_SPEND
  - thresholdPercent: 0.8  # 80% of budget
    spendBasis: CURRENT_SPEND
  - thresholdPercent: 1.0  # 100% of budget
    spendBasis: CURRENT_SPEND
allUpdatesRule:
  pubsubTopic: "projects/YOUR_PROJECT_ID/topics/budget-alerts"  # Optional: for programmatic alerts
  schemaVersion: "1.0"